services:
    app:
      build:
        context: ./app
        dockerfile: Dockerfile
      container_name: tom
      ports:
        - "8080:8080"
    bd:
      build:
        context: ./db
        dockerfile: Dockerfile
      container_name: vprodb
    memcached:
        image: memcached:latest
        container_name: vprocache01
    rabbitmq:
        image: rabbitmq:latest
        container_name: vpromq01
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - "80:80"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - app
          - memcached
          - rabbitmq
        
       
      


    